---
- hosts: all
  vars:
    ssh_key_filename: ed25519_key
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago

    - name: install base apps
      ansible.builtin.package:
        name:
          - btop
          - cmatrix
          - flatpak
          - fzf
          - git
          - htop
          - keychain
          - kitty
          - lsd
          - sudo
          - tmux
          - unzip
          - zoxide
          - zsh
        state: latest

    - name: OS specific stuff
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "tasks/{{ansible_facts['os_family'] }}.yml"
          - "tasks/default.yml"
          skip: true

    - name: Ensure Neovim source build directory exists
      ansible.builtin.file:
        path: /usr/local/src/neovim
        state: directory
        mode: '0755'

    - name: Clone Neovim stable source code
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: /usr/local/src/neovim
        version: stable
        depth: 1
      register: git_clone

    - name: Compile Neovim source code
      ansible.builtin.command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo
        chdir: /usr/local/src/neovim
      when: git_clone.changed

    - name: Install compiled Neovim binary
      ansible.builtin.command:
        cmd: make install
        chdir: /usr/local/src/neovim
      when: git_clone.changed

    - name: Download and install chezmoi to /usr/local/bin
      ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
      become: true
      args:
        creates: "/usr/local/bin/chezmoi"

    - name: Ensure ~/.local/bin is in PATH for this session
      # This ensures the next task can find the binary immediately
      ansible.builtin.set_fact:
        ansible_env: "{{ ansible_env | combine({'PATH': ansible_env.HOME + '/.local/bin:' + ansible_env.PATH}) }}"

    - name: Download and install Starship
      ansible.builtin.shell: |
        curl -sS https://starship.rs/install.sh | sh -s -- -y
      args:
        creates: /usr/local/bin/starship

    - name: Ensure Starship is executable
      ansible.builtin.file:
        path: /usr/local/bin/starship
        mode: '0755'
        owner: root
        group: root

    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"

    - name: add user zyzyx
      ansible.builtin.user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes

    - name: Create ~/.ssh
      ansible.builtin.file:
        path: /home/zyzyx/.ssh
        state: directory
        owner: zyzyx
        group: zyzyx
        mode: '0710'

    - name: add ssh key to authorised_keys
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"

    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "zyzyx"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        force: yes

    - name: GHPush echo
      ansible.builtin.debug:
        msg: "ghpush {{ lookup('ansible.builtin.file', '/home/zyzyx/.ssh/ed25519_key.pub') }} zyzyx@{{ansible_hostname}}"

    - name: Ensure Ansible remote tmp directory exists with correct permissions
      ansible.builtin.file:
        path: /home/zyzyx/.ansible/tmp
        state: directory
        mode: '0755'
        owner: zyzyx
        group: zyzyx
      become: false  # Runs as the standard user to maintain correct directory ownership

    - name: Initialize and apply Chezmoi dotfiles
      become: true
      become_user: zyzyx
      ansible.builtin.shell:
        cmd: chezmoi init --apply https://github.com/zyzyx159/chezmoi.git
        creates: "/home/zyzyx/.local/share/chezmoi" # Skips if already initialized

