---
- hosts: all
  vars:
    ssh_key_filename: ed25519_key
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: install base apps
      apt:
        name:
          - cmatrix
          - flatpak
          - git
          - htop
          - kitty
          - lsd
          - sudo
          - tmux
          - unzip
          - zsh
        state: latest
    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: add user zyzyx
      ansible.builtin.user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: Create ~/.ssh
      ansible.builtin.file:
        path: /home/zyzyx/.ssh
        state: directory
        owner: zyzyx
        group: zyzyx
        mode: '0710'
    - name: add ssh key to authorised_keys
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "zyzyx"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        force: yes
    - name: GHPush echo
      ansible.builtin.debug:
        msg: "ghpush {{ lookup('ansible.builtin.file', '/home/zyzyx/.ssh/ed25519_key.pub') }} zyzyx@{{ansible_hostname}}"

