---
- hosts: all
  vars:
    ssh_key_filename: ed25519_key
  tasks:
    - name: set time zone to America/Chicago
      timezone:
        name: America/Chicago
    - name: install base apps
      ansible.builtin.package:
        name:
          - btop
          - cmatrix
          - flatpak
          - git
          - htop
          - kitty
          - lsd
          - sudo
          - tmux
          - unzip
          - zsh
        state: latest
    - name: OS specific stuff
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files:
          - "tasks/{{ansible facts['os_family'] }}.yml"
          - "tasks/default.yml"
          skip: true
    - name: Ensure Neovim source build directory exists
      ansible.builtin.file:
        path: /usr/local/src/neovim
        state: directory
        mode: '0755'
    - name: Clone Neovim stable source code
      ansible.builtin.git:
        repo: 'https://github.com/neovim/neovim.git'
        dest: /usr/local/src/neovim
        version: stable
        depth: 1
      register: git_clone
    - name: Compile and install Neovim from source
      ansible.builtin.command:
        cmd: make CMAKE_BUILD_TYPE=RelWithDebInfo && make install
        chdir: /usr/local/src/neovim
      # Only compiles if the source directory changed or updated
      when: git_clone.changed
    - name: Download and install chezmoi
      ansible.builtin.shell: sh -c "$(curl -fsLS get.chezmoi.io)"
      args:
        creates: "/usr/local/bin/chezmoi"
    - name: download and install starship
      ansible.builtin.shell: curl -sS https://starship.rs/install.sh | sudo sh
    - name: copy sshd_config file
      copy:
        src: files/sshd_config
        dest: /etc/ssh/
        owner: root
        group: root
        mode: "644"
    - name: add user zyzyx
      ansible.builtin.user:
        name: zyzyx
        shell: /bin/zsh
        groups: sudo
        append: yes
    - name: Create ~/.ssh
      ansible.builtin.file:
        path: /home/zyzyx/.ssh
        state: directory
        owner: zyzyx
        group: zyzyx
        mode: '0710'
    - name: add ssh key to authorised_keys
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        name: "zyzyx"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_file: .ssh/{{ssh_key_filename}}
        force: yes
    - name: GHPush echo
      ansible.builtin.debug:
        msg: "ghpush {{ lookup('ansible.builtin.file', '/home/zyzyx/.ssh/ed25519_key.pub') }} zyzyx@{{ansible_hostname}}"
    - name: Initialize and apply Chezmoi dotfiles
      become: true
      become_user: zyzyx
      ansible.builtin.shell:
        cmd: chezmoi init --apply git@github.com:zyzyx159/chezmoi.git
        creates: "/home/zyzyx/.local/share/chezmoi" # Skips if already initialized

