---
- name: "run local"
  hosts: localhost
  connection: local
  tasks:
    - name: change shell
      user:
        name: zyzyx
        shell: /bin/zsh
    - name: add ssh key
      authorized_key:
        user: zyzyx
        state: present
        key: "{{ lookup('url', 'https://github.com/zyzyx159.keys', split_lines=False) }}"
    - name: install apps
      apt:
        name:
          - stow
          - zoxide
          - fzf
          - golang-go
        state: latest
    - name: Install lazygit from GitHub
      ansible.builtin.unarchive:
        src: "{{ lookup('url', 'https://api.github.com/repos/jesseduffield/lazygit/releases/latest', split_lines=false) | regex_search('browser_download_url.*(https://(.*?)_Linux_x86_64.tar.gz)', '\\1') | first }}"
            dest: /usr/local/bin/
                remote_src: true
                    include: lazygit
                        mode: '0755'   
    - name: make git folder
      ansible.builtin.file:
        path: /home/zyzyx/git/
        owner: zyzyx
        group: zyzyx
        state: directory
        mode: "0770"
    - name: install neovim
      ansible.builtin.git:
        repo: https://github.com/neovim/neovim
        dest: /home/zyzyx/git/neovim/
        version: stable
        force: yes
    - name: Build with RelWithDebInfo
      ansible.builtin.make:
        chdir: /home/zyzyx/git/neovim/
        params:
          CMAKE_BUILD_TYPE: "RelWithDebInfo"
    - name: Install with sudo
      ansible.builtin.make:
        chdir: /home/zyzyx/git/neovim/
        target: install
    - name: clone dotFiles
      ansible.builtin.git:
       repo: https://github.com/zyzyx159/dotFiles
       dest: /home/zyzyx/git/dotFiles
    - name: delete original dot files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - ~/.config/kitty/
        - ~/.config/nvim/
        - ~/.config/custScripts/
        - ~/.config/starship.toml
        - ~/.config/tmux/
        - ~/.zshrc
    - name: run Stow dotfiles
      ansible.buitin.shell: stow -d ~/git/dotFiles/Stow -t ~
      args:
        chdir: ~/git/dotFiles/Stow
